import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* Language Switcher */}
        <div className="absolute top-4 right-4 z-50">
          <a
            href="https://adpilote.com"
            className="px-3 py-1 text-sm text-gray-600 hover:text-black"
          >
            EN
          </a>
          <span className="mx-2 text-gray-400">|</span>
          <a
            href="https://adpilote.fr"
            className="px-3 py-1 text-sm text-gray-600 hover:text-black"
          >
            FR
          </a>
        </div>

        {children}

      </body>
    </html>
  );
}